volumes:
  claude:
    name: claude

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - claude:/root/.claude
      - ~/.local/bin/claude:/root/.local/bin/claude:ro
      - ~/.android:/root/.android
    devices:
      - /dev/kvm
    group_add:
      - "992"
    network_mode: host
    command: sleep infinity
